image: docker:20.10.16
services:
  - docker:20.10.16-dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker info
    - docker-compose -f docker-compose.yml build

deploy:
  stage: deploy
  script:
    - echo "✅ Containers are built — Add deploy commands if needed"
