image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

build_app:
  stage: build
  script:
    - docker info
    - docker compose -f docker-compose.yml build
  only:
    - master

deploy_app:
  stage: deploy
  script:
    - docker compose -f docker-compose.yml up -d
  only:
    - master
