stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

build_app:
  stage: build
  image: docker:latest
  script:
    - docker info
    - docker compose build
  only:
    - master

deploy_app:
  stage: deploy
  image: docker:latest
  script:
    - docker compose up -d
  only:
    - master
